[package]
name = "decadog"
version = "0.1.0"
authors = ["Tom Milligan <tom@reinfer.io>"]
edition = "2018"

[dependencies]
dialoguer = "0.5.0"
github-rs = "0.7.0"
reqwest = "0.9.22"
serde = "1.0.102"
serde_derive = "1.0.102"
serde_json = "1.0.41"

[dev-dependencies]
pretty_assertions = "0.6.1"
